### ISSUE TITLE
VR Navigation

### ISSUE THREAD

**Issue by DubiousTunic** [vasturiano/3d-force-graph-vr#22]
Hi, I am wondering if there's any chance of letting the VR User navigate through the space using the VR controllers? That would be awesome, just like the rest of your work, thank you!

**Comment by vasturiano** [comment]
@DubiousTunic thanks for reaching out.

The module should already have that functionality. It's using Aframe's extras [movement-controls](https://github.com/n5ro/aframe-extras/tree/master/src/controls) which provides exactly the ability to "fly" through space using VR controllers gamepad controls, as well as plain keyboard equivalent wasd keys.

I've just tested this in my Oculus and it does work as expected, using the right-hand controller gamepad stick. Is it not working for you? Which VR controllers are you using?

**Comment by DubiousTunic** [comment]
Hello, I tried this on my Oculus Rift with Oculus Touch controllers using the StreamVR app and I couldn't fly around. I can on the other hand fly around using the keyboard.

**Comment by eviltik** [comment]
Use your head orientation to choose your destination while moving. That's just excellent.

**Comment by olbeimarton** [comment]
Hi there,

Love the software, but unfortunately I cannot move either using the joystick (Meta Quest 2). I tried it on the example above (https://vasturiano.github.io/3d-force-graph-vr/example/large-graph/) from the headset. Works fine from the desktop browser using the keyboard. I'd like to ask if you have any suggestions how to resolve this.

**Comment by vasturiano** [comment]
@olbeimarton I've just pushed a fix which should get the joystick movement controls working again. Issue was an incompatibility with the gamepad controls in `aframe-extras` and the latest version of Aframe `1.4.1`.

Let me know if it works for you.

**Comment by olbeimarton** [comment]
Thank you very much @vasturiano, it works! I really appreciate the fix, thanks again.
