### ISSUE TITLE
Adding a video behind the graph

### ISSUE THREAD

**Issue by malani-art** [vasturiano/3d-force-graph-vr#23]
Hey! I believe this should be a quick question, simple solution, but I can't seem to add a video BEHIND the graph/a background video.

My code in Graph.js:

    // Display
      width={width}
      height={height}
      backgroundColor={"#background-video"}
      showNavInfo={false}

In style.scss:

#background-video {
    width: 100vw;
    height: 100vh;
    object-fit: cover;
    position: absolute;
    left: 0;
    right: 0;
    top: 0;
    bottom: 0;
    z-index: -1;

Despite making it backgroundColor and z-index -1, the video still appears in front of the graph.

Any ideas?

Thank you

**Comment by vasturiano** [comment]
@malani-art you'll probably want to make the globe component background transparent, like so:
```js
backgroundColor="rgba(0,0,0,0)"
```

**Comment by malani-art** [comment]
@vasturiano YES! It worked. Thank you!
