### ISSUE TITLE
Adding <!DOCTYPE html> at the top of the source code causes basic example to fail

### ISSUE THREAD

**Issue by micrology** [vasturiano/3d-force-graph-vr#30]
**Describe the bug**
The HTML 5 standard [requires](https://developer.mozilla.org/en-US/docs/Glossary/Doctype) an informational declaration `<!DOCTYPE html>` at the start of an html file. 
The source file provided on the [README](https://github.com/vasturiano/3d-force-graph-vr) page for the basic example does not include this declaration - it starts with the `<head>` element.  To my astonishment, if you add the missing declaration (and the required `<html>` and `</html>` elements) the example no longer works - the generated web page is blank although there are no errors reported in the console.
**To Reproduce**
Copy the [basic example](https://github.com/vasturiano/3d-force-graph-vr/blob/master/example/basic/index.html) into a file, prepend `<!DOCTYPE html><html>` and append `</html>`, and then access this file through a browser.  You will see a blank, white page.

**Expected behavior**
The same as the file without these additions.

**Desktop (please complete the following information):**
 - OS: Mac OS Monterey
 - Browser Any (tested on Chrome and Firefox) with WebXR emulator extension
 - Version 98

**Additional context**
I am mystified what could cause this to happen - and Google hasn't helped.  It took me a long time to discover that the apparently innocuous `DOCTTYPE` declaration was causing grief!

**Comment by vasturiano** [comment]
@micrology thanks for your report.

I can imagine it was difficult to trace the source of the issue back to the `DOCTYPE` declaration. I've just fixed the problem. 

Essentially, some `width`, `height` css properties were being set without the respective units (px). This generally works fine in most browsers and thus remained undetected, but was causing an issue in Aframe (the VR framework) if the DOCTYPE was set to html, because it relies on monitoring the DOM properties in the background.

You can see the simple fix here: https://github.com/vasturiano/3d-force-graph-vr/commit/d84a7f22d25efd2db0bf8d49a63255214d71d72f

So, if you upgrade to the latest version of this module you should no longer experience the issue.

**Comment by micrology** [comment]
Thanks – it works now.


Professor Nigel Gilbert, CBE, ScD, FREng, FAcSS, Professor of Sociology,
University of Surrey, Guildford GU2 7XH, UK. +44 (0)1483 689173

From: Vasco Asturiano ***@***.***>
Date: Monday, 7 February 2022 at 21:56
To: vasturiano/3d-force-graph-vr ***@***.***>
Cc: Gilbert, Nigel Prof (Sociology) ***@***.***>, Mention ***@***.***>
Subject: Re: [vasturiano/3d-force-graph-vr] Adding <!DOCTYPE html> at the top of the source code causes basic example to fail (Issue #30)

@micrology<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrology&data=04%7C01%7Cn.gilbert%40surrey.ac.uk%7C9f53e033ea824a01477308d9ea84a9b9%7C6b902693107440aa9e21d89446a2ebb5%7C0%7C0%7C637798677767038110%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=xtYXnRzQqmAsXSNiwpp5Gl9KJcjF3naim9sOz%2FLWnQo%3D&reserved=0> thanks for your report.

I can imagine it was difficult to trace the source of the issue back to the DOCTYPE declaration. I've just fixed the problem.

Essentially, some width, height css properties were being set without the respective units (px). This generally works fine in most browsers and thus remained undetected, but was causing an issue in Aframe (the VR framework) if the DOCTYPE was set to html, because it relies on monitoring the DOM properties in the background.

You can see the simple fix here: d84a7f2<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvasturiano%2F3d-force-graph-vr%2Fcommit%2Fd84a7f22d25efd2db0bf8d49a63255214d71d72f&data=04%7C01%7Cn.gilbert%40surrey.ac.uk%7C9f53e033ea824a01477308d9ea84a9b9%7C6b902693107440aa9e21d89446a2ebb5%7C0%7C0%7C637798677767038110%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=QFQOrm2IysmOzzK4J7jVnjeSBTSsr6LCyQ5T4RHwCBI%3D&reserved=0>

So, if you upgrade to the latest version of this module you should no longer experience the issue.

—
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvasturiano%2F3d-force-graph-vr%2Fissues%2F30%23issuecomment-1031971287&data=04%7C01%7Cn.gilbert%40surrey.ac.uk%7C9f53e033ea824a01477308d9ea84a9b9%7C6b902693107440aa9e21d89446a2ebb5%7C0%7C0%7C637798677767038110%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=YTf9fcDw9XOnkaMtW2ih6KEMcsrnQ2JgMStL58ZN%2F3M%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAALCAAVXQBD6G3EOO4ZTDB3U2A5X3ANCNFSM5NV3V3XA&data=04%7C01%7Cn.gilbert%40surrey.ac.uk%7C9f53e033ea824a01477308d9ea84a9b9%7C6b902693107440aa9e21d89446a2ebb5%7C0%7C0%7C637798677767038110%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=kyGRbqn54DLVG%2BZYZk6r73JtwBwRtbWakOCFe9%2BJLGQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cn.gilbert%40surrey.ac.uk%7C9f53e033ea824a01477308d9ea84a9b9%7C6b902693107440aa9e21d89446a2ebb5%7C0%7C0%7C637798677767038110%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=bT8v5nGhZGYZFDzQUF%2FybiQGHaY7abEbMFXNi74g4ms%3D&reserved=0> or Android<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cn.gilbert%40surrey.ac.uk%7C9f53e033ea824a01477308d9ea84a9b9%7C6b902693107440aa9e21d89446a2ebb5%7C0%7C0%7C637798677767038110%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Zy1Ms3eTSPv98CQuJnnsaQbC4lJTyzjxzC5mOvTHB7U%3D&reserved=0>.
