### ISSUE TITLE
Text + Nodes causes errors

### ISSUE THREAD

**Issue by malani-art** [vasturiano/3d-force-graph-vr#32]
Hello,

For some reason, when I try to implement nodes and text at the same time, it throws this error:

THREE.Sprite: "Raycaster.camera" needs to be set in order to raycast against sprites.
Uncaught TypeError: e.camera is null

You can see this happening in the example too: https://vasturiano.github.io/3d-force-graph-vr/example/text-links/

Any idea how I can fix this? I'd ideally like to have both the sphere nodes and text apparent.

Thank you!

**Comment by vasturiano** [comment]
@malani-art please see https://github.com/vasturiano/3d-force-graph-vr/issues/21 and https://github.com/vasturiano/3d-force-graph-vr/issues/31.
