### ISSUE TITLE
Differentiating same name nodes

### ISSUE THREAD

**Issue by malani-art** [vasturiano/3d-force-graph-vr#36]
Hi,

I'm not sure if this already exists but I'm making a family tree using this 3d force graph and I have family members with the same names. Because of that, the node links connect the wrong names together, confusing them. Is there a way to differentiate same name nodes? If not, adding a way to do that would be great!

Thanks

**Comment by vasturiano** [comment]
@malani-art you should be using unique ids for the nodes, not names that can be repeated. Each node should have it's own unique identifier attribute that you should use to reference from the links structure.
