### ISSUE TITLE
Can't move while in Oculus Rift

### ISSUE THREAD

**Issue by nirba27** [vasturiano/3d-force-graph-vr#4]
Hey,

I tried to play the graph using Oculus Rift ,
Everything works fine except off the touch handles that have no response when trying to move back and forward around the graph.
While not in vr mode the touch handles works fine.
Any ideas for a solution ?

**Comment by vasturiano** [comment]
@nirba27 thanks for the report. I've upgraded the controllers used to control the movement. Just let me know if you are still experiencing any issues with the latest version (`1.17.0`).

**Comment by nirba27** [comment]
WOW! it works amazing now , thank you so much for your help !!!

**Comment by micahstubbs** [comment]
@vasturiano you can probably close this issue too, since @nirba27 is happy with the outcome 😄
