### ISSUE TITLE
Is there a way to render the passthrough background for XR headsets (e.g. Oculus Pro)?

### ISSUE THREAD

**Issue by damienstanton** [vasturiano/3d-force-graph-vr#48]
**Is your feature request related to a problem? Please describe.**
For an upcoming demo this would be useful.

**Describe the solution you'd like**
I am wondering if something like [this](https://codesandbox.io/s/8w8hm?file=/src/App.tsx) is available in `3d-force-graph-vr`.

**Describe alternatives you've considered**
(See link)

**Additional context**
It would be useful to render the graph with the passthrough camera feed as the background. Not sure how `react-xr` does it but I imagine it would just require a tweak to the underlying three render object. Not sure if we can currently do that from the `3d-force-graph-vr` API. If so, please let me know as this would be great!

**Comment by vasturiano** [comment]
@damienstanton this repo uses [A-Frame](https://aframe.io/) as a framework around the WebXR functionality.
So, do you have an idea on how this passthrough background might be achieved with A-Frame?
