### ISSUE TITLE
Re-enable touch screen movement controls?

### ISSUE THREAD

**Issue by apowers313** [vasturiano/3d-force-graph-vr#52]
Looks like [the issue](https://github.com/c-frame/aframe-extras/commit/51e9f4dce7e9de5e941fe20f558a1b388d1e80dd) causing [touch screen movement controls to break](https://github.com/vasturiano/3d-force-graph-vr/blob/dce4946f4e3e64082bad771cb8a7aeeee2334c45/src/3d-force-graph-vr.js#L12) in c-frame has been fixed and released.

Maybe we can re-enable them now?

**Comment by vasturiano** [comment]
@apowers313 thanks for reaching out. Touch controls to move are now re-enabled. 👍
